# Generated by Django 5.0.6 on 2024-06-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_result_maths_result_value_error_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
